/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;
import java.awt.*;
import javax.swing.*;
import java.awt.event.*;
import javax.swing.border.*;
import javax.swing.table.*;

import connection.KetnoiKaraoke;
import controller.Dichvu_Controller;
/**
 *
 * @author Quang
 */
public class Dichvu extends javax.swing.JInternalFrame {

  Dichvu_Controller adapterMd=new Dichvu_Controller ();
        KetnoiKaraoke adapterCtr=new KetnoiKaraoke();
	private String chonDichvu;
	private String chonDvvD;
	private JTextField txtDcKh;
    public Dichvu() {
        initComponents();
        setTitle("Dịch Vụ");
        setResizable(false);
		    adapterMd=new Dichvu_Controller();
		    tblDv.setModel(adapterMd.loadDichVu());  
		    adapterMd=new Dichvu_Controller();
		    tblDvDat.setModel(adapterMd.loadHdDv());
		    cmbNhanVien.setModel(adapterMd.loadNhanvienCmb());     
			}
	

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDv = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtTenDv = new javax.swing.JTextField();
        txtGiaDv = new javax.swing.JTextField();
        btnThemDv = new javax.swing.JButton();
        btnXoaDv = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblDvDat = new javax.swing.JTable();
        btnDatDv = new javax.swing.JButton();
        btnHuyDv = new javax.swing.JButton();
        btnXemHd = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblTt = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        cmbNhanVien = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblTongtien = new javax.swing.JLabel();
        lblSldv = new javax.swing.JLabel();
        lblNv = new javax.swing.JLabel();
        btnXuat = new javax.swing.JButton();
        btnThanhtoansau = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 153, 51));
        jLabel2.setText("DỊCH VỤ");

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh sách dịch vụ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        tblDv.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Id", "Tên DV", "Giá DV"
            }
        ));
        tblDv.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDvMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblDv);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Nhập Dịch Vụ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Tên DV:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Giá DV:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtTenDv, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                    .addComponent(txtGiaDv))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtTenDv, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtGiaDv, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(39, 39, 39))
        );

        btnThemDv.setBackground(new java.awt.Color(255, 153, 51));
        btnThemDv.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnThemDv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/plus.png"))); // NOI18N
        btnThemDv.setText("Thêm");
        btnThemDv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemDvActionPerformed(evt);
            }
        });

        btnXoaDv.setBackground(new java.awt.Color(255, 153, 51));
        btnXoaDv.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnXoaDv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/delete.png"))); // NOI18N
        btnXoaDv.setText("Xóa");
        btnXoaDv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaDvActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(255, 153, 0));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/loop2.png"))); // NOI18N
        jButton3.setText("Cập nhật");

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Danh Sách Dịch Vụ Vừa Đặt", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        tblDvDat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id", "Tên DV", "Thời Gian đặt", "Ngày Đặt"
            }
        ));
        tblDvDat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblDvDatMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblDvDat);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 479, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 27, Short.MAX_VALUE))
        );

        btnDatDv.setBackground(new java.awt.Color(255, 153, 51));
        btnDatDv.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnDatDv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/redo2.png"))); // NOI18N
        btnDatDv.setText("Đặt Dịch vụ");
        btnDatDv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDatDvActionPerformed(evt);
            }
        });

        btnHuyDv.setBackground(new java.awt.Color(255, 153, 51));
        btnHuyDv.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnHuyDv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/undo2.png"))); // NOI18N
        btnHuyDv.setText("Hủy Dịch Vụ");
        btnHuyDv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHuyDvActionPerformed(evt);
            }
        });

        btnXemHd.setBackground(new java.awt.Color(255, 153, 51));
        btnXemHd.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnXemHd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/eye.png"))); // NOI18N
        btnXemHd.setText("Xem Hóa Đơn");
        btnXemHd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXemHdActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Hóa Đơn Dịch Vụ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Hóa Đơn Dịch Vụ Karaoke");

        tblTt.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Dịch vụ", "Đơn Giá", "Thời Gian Đặt"
            }
        ));
        jScrollPane3.setViewportView(tblTt);

        jLabel5.setText("Người Lập Phiếu");

        cmbNhanVien.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chọn Nv:" }));
        cmbNhanVien.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbNhanVienItemStateChanged(evt);
            }
        });

        jLabel6.setText("Số Lượng DV");

        jLabel7.setText("Tổng Tiền");

        lblTongtien.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTongtien.setText("0 VNĐ");

        lblSldv.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblSldv.setText("0");

        lblNv.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblNv.setText(".");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(cmbNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblNv, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(56, 56, 56)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblTongtien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblSldv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 87, Short.MAX_VALUE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(154, 154, 154)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cmbNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(lblSldv))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(lblTongtien))
                        .addGap(0, 11, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(lblNv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );

        btnXuat.setBackground(new java.awt.Color(255, 153, 51));
        btnXuat.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnXuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/print.png"))); // NOI18N
        btnXuat.setText("Thanh Toán");
        btnXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXuatActionPerformed(evt);
            }
        });

        btnThanhtoansau.setBackground(new java.awt.Color(255, 153, 51));
        btnThanhtoansau.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnThanhtoansau.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/home.png"))); // NOI18N
        btnThanhtoansau.setText("Chọn Phòng");
        btnThanhtoansau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThanhtoansauActionPerformed(evt);
            }
        });

        jButton9.setBackground(new java.awt.Color(255, 153, 51));
        jButton9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/exit.png"))); // NOI18N
        jButton9.setText("Kết Thúc");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3)
                .addGap(42, 42, 42))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnThemDv, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnXoaDv, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(btnXuat)
                        .addGap(28, 28, 28)
                        .addComponent(btnThanhtoansau)
                        .addGap(37, 37, 37)
                        .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(85, 85, 85)
                                .addComponent(btnDatDv)
                                .addGap(18, 18, 18)
                                .addComponent(btnHuyDv)
                                .addGap(18, 18, 18)
                                .addComponent(btnXemHd))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 19, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnHuyDv)
                            .addComponent(btnXemHd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnDatDv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThemDv, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnXoaDv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnXuat)
                    .addComponent(btnThanhtoansau, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton9))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnThemDvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemDvActionPerformed
         if(txtTenDv.getText().equals("")|| txtGiaDv.getText().equals("")) 
                        {
                            if(txtTenDv.getText().equals(""))
                                JOptionPane.showMessageDialog(null,"vui lòng nhập tên dịch vụ");
                            else 
                                JOptionPane.showMessageDialog(null,"vui lòng nhập giá dịch vụ" );
                                
                        }
                            else if (JOptionPane.showConfirmDialog(null, "Bạn có chắc muốn thêm!","Kiểm tra lại",
				        JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION) {
					adapterMd.ThemDichVu(txtTenDv.getText().toString(),txtGiaDv.getText().toString());
					adapterMd=new Dichvu_Controller();
					tblDv.setModel(adapterMd.loadDichVu());
				}
    }//GEN-LAST:event_btnThemDvActionPerformed

    private void btnXoaDvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaDvActionPerformed
    int dialogButton = JOptionPane.YES_NO_OPTION;
		        JOptionPane.showConfirmDialog (null, "Kiểm tra lại các mặt hàng chưa thanh toán trc khi xóa!","Cẩn thận!",dialogButton);
		        if(dialogButton == JOptionPane.YES_OPTION){
			adapterMd.XoaId("tb_dichvu","ma_dv",chonDichvu);
			adapterMd=new Dichvu_Controller();
			tblDv.setModel(adapterMd.loadDichVu());
			}
    }//GEN-LAST:event_btnXoaDvActionPerformed

    private void tblDvMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDvMouseClicked
       chonDichvu=tblDv.getModel().getValueAt(tblDv.getSelectedRow(),0).toString();
    }//GEN-LAST:event_tblDvMouseClicked

    private void cmbNhanVienItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbNhanVienItemStateChanged
       if(cmbNhanVien.getSelectedIndex()==0) lblNv.setText("");
				else lblNv.setText(cmbNhanVien.getSelectedItem().toString());
    }//GEN-LAST:event_cmbNhanVienItemStateChanged

    private void btnXemHdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXemHdActionPerformed
 adapterMd=new Dichvu_Controller();
			  tblTt.setModel(adapterMd.loadTtDv());
			
			  lblSldv.setText(adapterCtr.demDong("tb_hoadondv",adapterCtr.demHddv));
                          lblTongtien.setText(adapterCtr.demTien(adapterCtr.demtien1)+" VNĐ");
			
    }//GEN-LAST:event_btnXemHdActionPerformed

    private void btnDatDvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDatDvActionPerformed
   adapterMd.ThemHoaDonDv(chonDichvu,adapterCtr.gioHt,adapterCtr.ngayHt);
		adapterMd=new Dichvu_Controller();
		tblDvDat.setModel(adapterMd.loadHdDv());
    }//GEN-LAST:event_btnDatDvActionPerformed

    private void btnHuyDvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHuyDvActionPerformed
           adapterMd.XoaId("tb_hoadondv","ma_hddv",chonDvvD);
		adapterMd=new Dichvu_Controller();
		tblDvDat.setModel(adapterMd.loadHdDv()); // TODO add your handling code here:
    }//GEN-LAST:event_btnHuyDvActionPerformed

    private void btnXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXuatActionPerformed
      lblSldv.setText("");
				lblTongtien.setText("");
				adapterMd.XoaHddv();
				tblDvDat.setModel(adapterMd.loadHdDv());
				JOptionPane.showMessageDialog(null, "Đã in!");
    }//GEN-LAST:event_btnXuatActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
       dispose();
    }//GEN-LAST:event_jButton9ActionPerformed

    private void btnThanhtoansauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThanhtoansauActionPerformed
        adapterMd=new Dichvu_Controller();
			tblDvDat.setModel(adapterMd.loadHdDv());
			dichvuphong chonphong=new dichvuphong();
			chonphong.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
			chonphong.setVisible(true);
			chonphong.setLocationRelativeTo(null);
			
    }//GEN-LAST:event_btnThanhtoansauActionPerformed

    private void tblDvDatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblDvDatMouseClicked
       chonDvvD=tblDvDat.getModel().getValueAt(tblDvDat.getSelectedRow(),0).toString();
    }//GEN-LAST:event_tblDvDatMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDatDv;
    private javax.swing.JButton btnHuyDv;
    private javax.swing.JButton btnThanhtoansau;
    private javax.swing.JButton btnThemDv;
    private javax.swing.JButton btnXemHd;
    private javax.swing.JButton btnXoaDv;
    private javax.swing.JButton btnXuat;
    private javax.swing.JComboBox<String> cmbNhanVien;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblNv;
    private javax.swing.JLabel lblSldv;
    private javax.swing.JLabel lblTongtien;
    private javax.swing.JTable tblDv;
    private javax.swing.JTable tblDvDat;
    private javax.swing.JTable tblTt;
    private javax.swing.JTextField txtGiaDv;
    private javax.swing.JTextField txtTenDv;
    // End of variables declaration//GEN-END:variables
}
