/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

     import javax.swing.JOptionPane;


import connection.KetnoiKaraoke;
import controller.TruyvanKaraoke;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
/**
 *
 * @author Quang
 */
public class FormMain extends javax.swing.JFrame {
     TruyvanKaraoke adapterMd;
	KetnoiKaraoke adapterCtr;
        String chonPhong=new String();
	String chonNhanvien=new String();
	String chonKhachhang="";
	int demHangTbKh;

    /**
     * Creates new form FormMain1
     */
    public FormMain() {
        initComponents();
        setTitle("ỨNG DỤNG QUẢN LÝ KARAOKE");
        addWindowListener(new WindowAdapter() {
			// Show list customer, room, staff, room booked
			@Override
			public void windowOpened(WindowEvent arg0) {
				adapterMd=new TruyvanKaraoke();
				tblKh.setModel(adapterMd.loadKhachhang());
				adapterMd=new TruyvanKaraoke();
				tblPhongtrong.setModel(adapterMd.loadPhong("0"));
				adapterMd=new TruyvanKaraoke();
				tblNvDp.setModel(adapterMd.loadNhanVien());
				adapterMd=new TruyvanKaraoke();
				tblDSPD.setModel(adapterMd.loadDSDatPhong());	
				adapterCtr=new KetnoiKaraoke();
			}
		});
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Desktop = new javax.swing.JDesktopPane();
        btnNewButton = new javax.swing.JButton();
        jPanel_9 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblKh = new javax.swing.JTable();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblPhongtrong = new javax.swing.JTable();
        jPanel13 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblNvDp = new javax.swing.JTable();
        button_1 = new javax.swing.JButton();
        btnLammoi = new javax.swing.JButton();
        jPanel14 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblDSPD = new javax.swing.JTable();
        btnNewButton_6 = new javax.swing.JButton();
        btnNewButton_5 = new javax.swing.JButton();
        btnNewButton_3 = new javax.swing.JButton();
        btnNewButton_4 = new javax.swing.JButton();
        btnNewButton_1 = new javax.swing.JButton();
        btnNewButton_2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnNewButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/exit.png"))); // NOI18N
        btnNewButton.setText("Đăng Xuất");
        btnNewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewButtonActionPerformed(evt);
            }
        });

        jPanel_9.setBorder(javax.swing.BorderFactory.createTitledBorder("Đặt phòng"));

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Danh sách KH chờ"));

        tblKh.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Mã KH", "Tên KH", "Số Đt"
            }
        ));
        tblKh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblKhMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblKh);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Danh sách phòng trống"));

        tblPhongtrong.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Mã Phòng", "Tên Phòng", "Loại Phòng"
            }
        ));
        jScrollPane2.setViewportView(tblPhongtrong);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel13.setBorder(javax.swing.BorderFactory.createTitledBorder("Nhân viên phục vụ"));

        tblNvDp.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Mã NV", "Tên NV", "Chức vụ"
            }
        ));
        tblNvDp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblNvDpMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tblNvDp);

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel13Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1))
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel13Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        button_1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/bell.png"))); // NOI18N
        button_1.setText("Đặt Phòng");
        button_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_1ActionPerformed(evt);
            }
        });

        btnLammoi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/loop2.png"))); // NOI18N
        btnLammoi.setText("Cập Nhật");
        btnLammoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLammoiActionPerformed(evt);
            }
        });

        jPanel14.setBorder(javax.swing.BorderFactory.createTitledBorder("Danh Sách Phòng đã đặt"));

        tblDSPD.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Tên Phòng", "Loại Phòng", "Giá Phòng", "Ngày Đặt Phòng", "Giờ Đặt Phòng"
            }
        ));
        jScrollPane4.setViewportView(tblDSPD);

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addComponent(jScrollPane4)
                .addContainerGap())
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout jPanel_9Layout = new javax.swing.GroupLayout(jPanel_9);
        jPanel_9.setLayout(jPanel_9Layout);
        jPanel_9Layout.setHorizontalGroup(
            jPanel_9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_9Layout.createSequentialGroup()
                .addGroup(jPanel_9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel_9Layout.createSequentialGroup()
                        .addGroup(jPanel_9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel_9Layout.createSequentialGroup()
                                .addGap(225, 225, 225)
                                .addComponent(button_1)
                                .addGap(142, 142, 142)
                                .addComponent(btnLammoi)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel_9Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)))
                .addContainerGap())
        );
        jPanel_9Layout.setVerticalGroup(
            jPanel_9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_9Layout.createSequentialGroup()
                .addGroup(jPanel_9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(41, 41, 41)
                .addGroup(jPanel_9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(button_1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnLammoi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 20, Short.MAX_VALUE))
        );

        btnNewButton_6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/login.png"))); // NOI18N
        btnNewButton_6.setText("Khách Hàng");
        btnNewButton_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewButton_6ActionPerformed(evt);
            }
        });

        btnNewButton_5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/home.png"))); // NOI18N
        btnNewButton_5.setText("Phòng Hát");
        btnNewButton_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewButton_5ActionPerformed(evt);
            }
        });

        btnNewButton_3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/user.png"))); // NOI18N
        btnNewButton_3.setText("Nhân Viên");
        btnNewButton_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewButton_3ActionPerformed(evt);
            }
        });

        btnNewButton_4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/food.png"))); // NOI18N
        btnNewButton_4.setText("Dịch Vụ");
        btnNewButton_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewButton_4ActionPerformed(evt);
            }
        });

        btnNewButton_1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/user4.png"))); // NOI18N
        btnNewButton_1.setText("Tài Khoản");
        btnNewButton_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewButton_1ActionPerformed(evt);
            }
        });

        btnNewButton_2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/print.png"))); // NOI18N
        btnNewButton_2.setText("Trả Phòng");
        btnNewButton_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewButton_2ActionPerformed(evt);
            }
        });

        Desktop.setLayer(btnNewButton, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Desktop.setLayer(jPanel_9, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Desktop.setLayer(btnNewButton_6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Desktop.setLayer(btnNewButton_5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Desktop.setLayer(btnNewButton_3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Desktop.setLayer(btnNewButton_4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Desktop.setLayer(btnNewButton_1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        Desktop.setLayer(btnNewButton_2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout DesktopLayout = new javax.swing.GroupLayout(Desktop);
        Desktop.setLayout(DesktopLayout);
        DesktopLayout.setHorizontalGroup(
            DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DesktopLayout.createSequentialGroup()
                .addGroup(DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(DesktopLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnNewButton_6)
                        .addGap(18, 18, 18)
                        .addComponent(btnNewButton_5)
                        .addGap(18, 18, 18)
                        .addComponent(btnNewButton_3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnNewButton_4, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnNewButton_1)
                        .addGap(30, 30, 30)
                        .addComponent(btnNewButton_2)
                        .addGap(18, 18, 18)
                        .addComponent(btnNewButton))
                    .addGroup(DesktopLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jPanel_9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        DesktopLayout.setVerticalGroup(
            DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DesktopLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                    .addComponent(btnNewButton_6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnNewButton_5, javax.swing.GroupLayout.DEFAULT_SIZE, 44, Short.MAX_VALUE)
                    .addComponent(btnNewButton_3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnNewButton_1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnNewButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnNewButton_2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnNewButton_4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel_9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Desktop)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Desktop)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewButtonActionPerformed
        int kq=JOptionPane.showConfirmDialog(this,"Bạn có muốn đăng xuất không?","Thông Báo",
            JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (kq==JOptionPane.YES_OPTION){
            dispose();
            Login frm = new Login();
            frm.setVisible(true);
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNewButtonActionPerformed

    private void btnNewButton_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewButton_1ActionPerformed
        QLTaiKhoan frm = new QLTaiKhoan();
        Desktop.add(frm);
        frm.setLocation((Desktop.getWidth()-frm.getWidth())/2,
            (Desktop.getHeight()-frm.getHeight())/2);
        frm.setVisible(true);
    }//GEN-LAST:event_btnNewButton_1ActionPerformed

    private void btnNewButton_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewButton_6ActionPerformed
     khachhang kh=new khachhang();
       Desktop.add(kh);
        kh.setLocation((Desktop.getWidth()-kh.getWidth())/2,
            (Desktop.getHeight()-kh.getHeight())/2);
        kh.setVisible(true);
    }//GEN-LAST:event_btnNewButton_6ActionPerformed

    private void tblKhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblKhMouseClicked
        chonKhachhang=tblKh.getModel().getValueAt(tblKh.getSelectedRow(),0).toString();
	    	
    }//GEN-LAST:event_tblKhMouseClicked

    private void tblNvDpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblNvDpMouseClicked
        JOptionPane.showMessageDialog(null,"NV "+tblNvDp.getModel().getValueAt(tblNvDp.getSelectedRow(),1).toString()+" vừa được chọn.");
    }//GEN-LAST:event_tblNvDpMouseClicked

    private void button_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_1ActionPerformed
        if (JOptionPane.showConfirmDialog(null, "Bạn có muốn đặt phòng này!","Kiểm tra lại",
	    JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION)		
	    {
        try
    	{
    	if(tblKh.getRowCount()==0)
    	{
    		JOptionPane.showMessageDialog(null, "Chưa thêm khách hàng!");
    	}
    	else
    	{
    		demHangTbKh=tblKh.getRowCount();
                chonPhong=tblPhongtrong.getModel().getValueAt(tblPhongtrong.getSelectedRow(),0).toString();
                chonNhanvien=tblNvDp.getModel().getValueAt(tblNvDp.getSelectedRow(),0).toString();
                adapterMd=new TruyvanKaraoke();
                adapterMd.ThemKhachNhanPhong(chonPhong,"0");
                adapterMd.ThemHopDong(chonPhong,chonNhanvien);
                adapterMd.updateKhachHang();
                adapterMd.updatePhong("1",chonPhong);
                adapterMd=new TruyvanKaraoke();
                tblKh.setModel(adapterMd.loadKhachhang());
                adapterMd=new TruyvanKaraoke();
                tblPhongtrong.setModel(adapterMd.loadPhong("0"));
                adapterMd=new TruyvanKaraoke();
                tblDSPD.setModel(adapterMd.loadDSDatPhong());	
                //hiển thị lại các phòng
                chonPhong=new String();
    	}
    	}
    		catch(Exception ex)
    			{
    			JOptionPane.showMessageDialog(null,"Phải chọn Phòng và Nhân viên, kiểm tra lại!");
    		    }
                	
                }
    }//GEN-LAST:event_button_1ActionPerformed

    private void btnLammoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLammoiActionPerformed
        adapterMd=new TruyvanKaraoke();
	    		tblKh.setModel(adapterMd.loadKhachhang());
	    		adapterMd=new TruyvanKaraoke();
	    		tblPhongtrong.setModel(adapterMd.loadPhong("0"));
	    		adapterMd=new TruyvanKaraoke();
	    		tblNvDp.setModel(adapterMd.loadNhanVien());
	    		adapterMd=new TruyvanKaraoke();
	    		tblDSPD.setModel(adapterMd.loadDSDatPhong());	
	    		
	    		adapterCtr=new KetnoiKaraoke();
    }//GEN-LAST:event_btnLammoiActionPerformed

    private void btnNewButton_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewButton_3ActionPerformed
      nhanvien nv=new nhanvien();
       Desktop.add(nv);
        nv.setLocation((Desktop.getWidth()-nv.getWidth())/2,
            (Desktop.getHeight()-nv.getHeight())/2);
        nv.setVisible(true);
    }//GEN-LAST:event_btnNewButton_3ActionPerformed

    private void btnNewButton_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewButton_5ActionPerformed
    Phong ph=new Phong();
       Desktop.add(ph);
        ph.setLocation((Desktop.getWidth()-ph.getWidth())/2,
            (Desktop.getHeight()-ph.getHeight())/2);
        ph.setVisible(true);
    }//GEN-LAST:event_btnNewButton_5ActionPerformed

    private void btnNewButton_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewButton_4ActionPerformed
         Dichvu dv=new Dichvu();
       Desktop.add(dv);
        dv.setLocation((Desktop.getWidth()-dv.getWidth())/2,
            (Desktop.getHeight()-dv.getHeight())/2);
        dv.setVisible(true);
    }//GEN-LAST:event_btnNewButton_4ActionPerformed

    private void btnNewButton_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewButton_2ActionPerformed
         Traphong tp=new Traphong();
       Desktop.add(tp);
        tp.setLocation((Desktop.getWidth()-tp.getWidth())/2,
            (Desktop.getHeight()-tp.getHeight())/2);
        tp.setVisible(true);
    }//GEN-LAST:event_btnNewButton_2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Desktop;
    private javax.swing.JButton btnLammoi;
    private javax.swing.JButton btnNewButton;
    private javax.swing.JButton btnNewButton_1;
    private javax.swing.JButton btnNewButton_2;
    private javax.swing.JButton btnNewButton_3;
    private javax.swing.JButton btnNewButton_4;
    private javax.swing.JButton btnNewButton_5;
    private javax.swing.JButton btnNewButton_6;
    private javax.swing.JButton button_1;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel_9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable tblDSPD;
    private javax.swing.JTable tblKh;
    private javax.swing.JTable tblNvDp;
    private javax.swing.JTable tblPhongtrong;
    // End of variables declaration//GEN-END:variables
}
